before_install: 
  - "git config --global user.email \"travis-ci@travis-ci.com\""
  - "git config --global user.name \"Travis CI\""
cache: 
  directories: "-'$HOME/.m2/repository"
dist: xenial
git: 
  submodules: false
jdk: 
  - oraclejdk8
  - openjdk8
  - openjdk11
language: java
